function [A1, A2, A3, A4] = calculateA(self, I, J, varargin)
    % 计算像素p_{i, j}的四个相似性参数 A1~A4
    getA1 = @(I, J) (abs(self.image_post(I, J + 1) - self.image_post(I - 2, J - 1)) ...
        - abs(self.image_post(I + 1, J + 2) - self.image_post(I - 1, J))) ...
        ./ (self.L - 1);
    getA2 = @(I, J) (abs(self.image_post(I + 1, J) - self.image_post(I - 1, J - 2)) ...
        - abs(self.image_post(I + 2, J + 1) - self.image_post(I, J - 1))) ...
        ./ (self.L - 1);
    getA3 = @(I, J) (abs(self.image_post(I, J - 1) - self.image_post(I - 2, J + 1)) ...
        - abs(self.image_post(I + 1, J - 2) - self.image_post(I - 1, J))) ...
        ./ (self.L - 1);
    getA4 = @(I, J) (abs(self.image_post(I + 1, J) - self.image_post(I - 1, J + 2)) ...
        - abs(self.image_post(I + 2, J - 1) - self.image_post(I, J + 1))) ...
        ./ (self.L - 1);

    A1 = arrayfun(getA1, I, J);
    A2 = arrayfun(getA2, I, J);
    A3 = arrayfun(getA3, I, J);
    A4 = arrayfun(getA4, I, J);
end
