function [p_] = calculateP(self, I, J, Whl, Whr, Wvu, Wul, varargin)
    % 计算预测像素值 p'
    getP = @(I, J, Whl, Whr, Wvu, Wul) ...
        Whl .* self.image_post(I, J - 1) + ...
        Whr .* self.image_post(I, J + 1) + ...
        Wvu .* self.image_post(I - 1, J) + ...
        Wul .* self.image_post(I + 1, J);

    p_ = arrayfun(getP, I, J, Whl, Whr, Wvu, Wul);

end
