function [Hl, Hr, Vu, Vl] = calculateHV(self, I, J, varargin)
    % 计算梯度权系数 Hl, Hr, Vu, Vl
    getHl = @(I, J) 1 ./ sqrt(1 + self.alpha .* (...
        abs(self.image_post(I - 1, J) - self.image_post(I - 1, J - 2)) + ...
        abs(self.image_post(I + 1, J) - self.image_post(I - 1, J - 2))));
    getHr = @(I, J) 1 ./ sqrt(1 + self.alpha .* (...
        abs(self.image_post(I - 1, J) - self.image_post(I - 1, J + 2)) + ...
        abs(self.image_post(I + 1, J) - self.image_post(I - 1, J + 2))));
    getVu = @(I, J) 1 ./ sqrt(1 + self.alpha .* (...
        abs(self.image_post(I, J - 1) - self.image_post(I - 2, J - 1)) + ...
        abs(self.image_post(I, J + 1) - self.image_post(I - 2, J + 1))));
    getVl = @(I, J) 1 ./ sqrt(1 + self.alpha .* (...
        abs(self.image_post(I, J - 1) - self.image_post(I + 2, J - 1)) + ...
        abs(self.image_post(I, J + 1) - self.image_post(I + 2, J + 1))));

    Hl = arrayfun(getHl, I, J);
    Hr = arrayfun(getHr, I, J);
    Vu = arrayfun(getVu, I, J);
    Vl = arrayfun(getVl, I, J);
end
